name: festora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0  # ou versão mais recente
  uuid: ^4.0.0
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  intl: ^0.20.2
  http: ^1.3.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2 # (ou a versão mais nova)
  font_awesome_flutter: ^10.7.0 # Adicionado para ícones como Google e Apple

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Inder
      fonts:
        - asset: assets/fonts/Inder-Regular.ttf
          style: normal
    - family: Inria Sans
      fonts:
        - asset: assets/fonts/inria/InriaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/inria/InriaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/inria/InriaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inria/InriaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/inria/InriaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/inria/InriaSans-BoldItalic.ttf
          weight: 700
          style: italic

  uses-material-design: true
  assets:
    - assets/images/